spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RayenMrad/config-repo.git
          default-label: master
          clone-on-start: true
        #native:
          #search-locations: "classpath:/config"
          #search-locations : file:///C:/Users/rayen/Desktop/Dsi33/SOA/rayen-spring-cloud/config-repo

server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: '*'