server:
  port: 8081

spring:
  profiles:
    active: "docker"  # Use ONLY docker profile
  config:
    import: "optional:configserver:${CONFIG_SERVICE_URL:http://configserver:9999}"  # CHANGED
  application:
    name: genre-ms
  datasource:
    url: 'jdbc:h2:mem:gendb;DB_CLOSE_ON_EXIT=FALSE'
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://eurekaserver:8761/eureka}  # CHANGED
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false
    #hostname: genres-ms
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'

build:
  version: 1.0

author:
  name: "rayen genre"
  email: "rayenmrad_genre80@gmail.com"